### PR TITLE
Use hyperkube for kube-proxy.

### PR DESCRIPTION
**Pull request by madhusudancs**
It makes it much easier to use kubernetes-anywhere for deployments.

### CODE REVIEW

**Comment by colemickens** [comment]
What is the `--resource-container` flag used for? I don't see it mentioned here: http://kubernetes.io/docs/admin/kube-proxy/

**Comment by madhusudancs** [comment]
It is a deprecated flag. I don't know what it does, but did not want to touch it without understanding it, so left it as is.

**Comment by colemickens** [comment]
Alright. LGTM then; I'm a fan of `hyperkube`.

**Comment by madhusudancs** [comment]
Thanks. Merging the PR.

**Pull request merged**
