### PR TITLE
Officially deprecate kube-anywhere

### PR DESCRIPTION
**Pull request by luxas**
@kubernetes/sig-cluster-lifecycle-pr-reviews 
/assign @timothysc @roberthbailey

### CODE REVIEW

**Comment by fabriziopandini** [comment]
+100

**Comment by detiber** [comment]
:shipit:

**Review by timothysc — APPROVED** [review]
/approve
/lgtm 

With extreme prejudice!

**Comment by luxas** [comment]
@timothysc can you send a quick email to kubernetes-dev about this?

**Pull request merged**
