### PR TITLE
Add tmp path to gce usage instructions

### PR DESCRIPTION
**Pull request by cmluciano**
I'm not sure if I did something wrong or if this is a bug. I only found a working  kubeconfig within the .tmp folder.

### CODE REVIEW

**Comment by cmluciano** [comment]
cc @mikedanese

**Comment by cmluciano** [comment]
Worked for me! updatedexport KUBECONFIG=$(make -s kubeconfig-path)

**Comment by pipejakob** [comment]
/lgtm

I don't have merge powers on this repo, so I defer to @mikedanese.

**Comment by cmluciano** [comment]
Ping @mikedanese

**Pull request closed without merging**
